### ISSUE TITLE
Unsure how to use exe flags [v2]

### ISSUE THREAD

**Issue by hornsilk** [UserR00T/UniversalUnityHooks#10]
I'm pretty confused on what the 3 inputs the UniversalUnityHooks.exe is looking for: my command is

.\UniversalUnityHooks.exe -t "C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Managed\Assembly-CSharp.dll" -i "C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Plugins\logger.dll" -o "C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Managed\Assembly-CSharp-New.dll"

but it's giving me Cannot create "C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Plugins\logger.dll" because a file or directory with the same name already exists., which makes me think I've incorrectly interpreted the -i, -o, and -t flags

**Comment by UserR00T** [comment]
Hi hornsilk,

In v2, `-o` is used to define the output directory. This however is set to the `Assembly-CSharp-New.dll` document in your command. This should be kept default (empty), or changed to the target directory where you want your files to be copied into. The description of the option goes as follows: "_Set the output directory for assemblies to be copied to. NOTE: This will also be the search directory. Recommended to keep default._" @ [Options.cs#L18](https://github.com/UserR00T/UniversalUnityHooks/blob/v2/UniversalUnityHooks/Options.cs#L18)

Also just out of interest, have you tried v3? This is an version I'm working on that should allow you more options in regards to injecting and customizing. Documentation is currently lacking, but I'll happily answer any questions you may have.

Thanks,
UserR00T

Edit: I forgot to mention, input (`-i`) should be the input directory, not a singular file. Because UUH will search for the files and directories itself, you can also remove all arguments from your command and execute it using `.\UniversalUnityHooks.exe`.

**Comment by hornsilk** [comment]
Thanks!
I removed the flags and just ran the program in the game directory, and got this error. Not sure what this means but I guess it's that I wrote my injection c# code wrong. 

>  INFO     Target assembly file: C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Managed\Assembly-CSharp.dll
>  INFO     Target plugins & search directory: C:\Program Files\Wizards of the Coast\MTGA\Plugins
> 
> 
>  ERROR    No attributes have been loaded in. Press any key to exit the program.
 
 P.S.
 I did consider using v3 but couldn't find any source files to download and didn't feel like building any more code than necessary this morning

**Comment by UserR00T** [comment]
Awesome :)
That error just means no attributes were found in your plugin. Are your types public so UUH can see them?

(3.0 can be fetched from the Github Actions artifacts: [[download]](https://github.com/UserR00T/UniversalUnityHooks/suites/3450331259/artifacts/81895222) [[build #18]](https://github.com/UserR00T/UniversalUnityHooks/actions/runs/1113763264))

**Comment by hornsilk** [comment]
Sorry I'm a little new to all this; neither of those v3 links look like they have an .exe in the folders,..... what am I missing?

**Comment by UserR00T** [comment]
Yep don't worry, you should run those through `dotnet`, so your command will look something like `dotnet UniversalUnityHooks.dll -- execute YOUR ARGUMENTS HERE`. On *unix based systems you could directly run it by using the binary: `./UniversalUnityHooks execute`.

**Comment by hornsilk** [comment]
> Are your types public so UUH can see them?
I think so...... 
My project is just one csharp file that currently just looks like this:
`
public class YourClass

{
	[Hook("Wotc.Mtga.PregameSequenceLogger.RegisterStartTime")]

	public static void RegisterStartTime(Wotc.Mtga.PregameSequenceLogger l)

	{

        String myKey = "Hello World Crepea";

        Debug.LogFormat("Timer {0} start {1}", new object[]

        {

            myKey,

            DateTime.Now.ToString("HH:mm:ss.fff")

        });

    }

}
`
where `Wotc.Mtga.PregameSequenceLogger.RegisterStartTime` is the name of a class / function that I found from `dnSpy`.

I'm building the project, then copying the `.dll` to the plugins folder that your exe is finding

**Comment by UserR00T** [comment]
That's weird, could you output your folder structure & full console output from UniversalUnityHooks?

**Comment by hornsilk** [comment]
[Relevant] Folder Structure:
> C:\Program Files\Wizards of the Coast\MTGA\
___________________________________________________MTGA_Data\
_________________________________________________________________Managed\
____________________________________________________________________________Assembly-CSharp.dll
____________________________________________________________________________[a bunch of other .dlls]
_________________________________________________________________Plugins\
__________________________________________________________________________logger.dll (which I copied in)
___________________________________________________UniversalUnityHooks.exe

I can also send you the output from something like `tree` but there would be a ton of stuff


Command I ran, with full log

> PS C:\Program Files\Wizards of the Coast\MTGA> .\UniversalUnityHooks.exe
Universal Unity Hooks v2.1.3.0
 INFO     Target assembly file: C:\Program Files\Wizards of the Coast\MTGA\MTGA_Data\Managed\Assembly-CSharp.dll
 INFO     Target plugins & search directory: C:\Program Files\Wizards of the Coast\MTGA\Plugins
 ERROR    No attributes have been loaded in. Press any key to exit the program.
 
 


(Still pretty confused on v3, the [downloaded] link downloads a folder doesn't contain UniversalUnityHooks.dll, and the [build#18] link sends me to a progress page, which I don't know what to do with)

**Comment by UserR00T** [comment]
Ah I see the issue, you used the wrong `Plugins` folder haha-- I'll mention it in the wiki just to be sure :)

It expects the plugin dlls to reside in `C:\Program Files\Wizards of the Coast\MTGA\Plugins`, not in the current folder it's in, `C:\Program Files\Wizards of the Coast\MTGA\MTGA_DATA\Plugins`.

(I'm sorry, v3 uses a different name: it should be `UniversalUnityHooks.Core.dll`. `UniversalUnityHooks.Attributes.dll` is the file you reference in your plugin for the attributes.)

**Comment by hornsilk** [comment]
ohmygosh it worked!!!! Thanks so much for all your help! :D
