### ISSUE TITLE
How can i use UniversalUnityHooks

### ISSUE THREAD

**Issue by ayuLiao** [UserR00T/UniversalUnityHooks#11]
Hi, I am backend coder, I want Hook a Unity Game on windows. I find this project, it cool, but I don't understand how to use it.

I download the universalUnityHooks exe, and use --help, but I don't know what next I should do.

![image](https://user-images.githubusercontent.com/19529872/141113200-65c5ac50-4b2e-4b72-885e-ac7cd9cae375.png)

Thanks!

**Comment by lewisdoesstuff** [comment]
I'd recommend checking the API reference in the v2 [README](https://github.com/UserR00T/UniversalUnityHooks/tree/v2).

The actual executable (IIRC) is only responsible for hooking and injecting. 
You'll need to create your plugin files and drop them into ./Plugins for UUH to generate the hooks.

**Comment by UserR00T** [comment]
Hi ayuLiao!

Like lew stated, this message indicates that there were no (_or no compatible*_) assemblies found. 
Is your "Plugins/" directory empty by any chance? If that's the case, UUH will have nothing to modify on the target dll. If there is an dll in this directory, UUH has been unable to find the correct public attributes. Try changing the verbosity to the highest level (-v 4) and checking the output.

Feel free to stay on version 3, however errors like these might be a bit confusing at first.

Thanks!
*_In this instance, incompatible dlls would also include dlls without any UUH directives/attributes._

**Comment by lewisdoesstuff** [comment]
Closing.
Feel free to re-open if you've got any other questions :)
